// 配置文件 - 从环境变量读取
module.exports = {
  DBHOST: process.env.DBHOST || '127.0.0.1',
  DBPORT: process.env.DBPORT || 27017,
  DBNAME: process.env.DBNAME || 'myqa',
  secret: process.env.JWT_SECRET || 'jjcyyds',
  AI_BASE_URL: process.env.AI_BASE_URL || '',
  AI_API_KEY: process.env.AI_API_KEY || '',
  AI_MODEL: process.env.AI_MODEL || '',
  AI_TIMEOUT_MS: Number(process.env.AI_TIMEOUT_MS || 30000),
  RAG_SERVICE_URL: process.env.RAG_SERVICE_URL || 'http://127.0.0.1:8001',
  RAG_SERVICE_TIMEOUT_MS: Number(process.env.RAG_SERVICE_TIMEOUT_MS || 30000),
  EMBEDDING_MODEL_NAME: process.env.EMBEDDING_MODEL_NAME || 'all-MiniLM-L6-v2',
  QDRANT_URL: process.env.QDRANT_URL || 'http://127.0.0.1:6333',
  QDRANT_PATH: process.env.QDRANT_PATH || './.qdrant',
  QDRANT_COLLECTION_NAME: process.env.QDRANT_COLLECTION_NAME || 'customer_service_knowledge',
  RAG_TOP_K: Number(process.env.RAG_TOP_K || 8),
  RAG_SCORE_THRESHOLD: Number(process.env.RAG_SCORE_THRESHOLD || 0.3),
  RAG_RERANK_ENABLED: process.env.RAG_RERANK_ENABLED === 'true',
}
